In [1]:
# !pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\krinal\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (2.1.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\krinal\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\krinal\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\krinal\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\krinal\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\krinal\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\krinal\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

dataset = [["Bread", "Milk", "Beer"],
            ["Bread", "Diapers", "Eggs"],
            ["Milk", "Diapers", "Beer", "Cola"],
            ["Bread", "Milk", "Diapers", "Beer"],
            ["Bread", "Milk", "Cola"]] # the datatype is List of Lists

In [3]:
te = TransactionEncoder()
te = te.fit(dataset)                    # Reads all unique items from the dataset
te_ary = te.transform(dataset)          # Converts array into hot coded matric
print(te.columns_)           # transaction = column an draw wise structure
print(te_ary)

['Beer', 'Bread', 'Cola', 'Diapers', 'Eggs', 'Milk']
[[ True  True False False False  True]
 [False  True False  True  True False]
 [ True False  True  True False  True]
 [ True  True False  True False  True]
 [False  True  True False False  True]]

In [4]:
df = pd.DataFrame(te_ary, columns=te.columns_)     # Panda dataframe
print(df.columns)
df

Index(['Beer', 'Bread', 'Cola', 'Diapers', 'Eggs', 'Milk'], dtype='object')

    Beer  Bread   Cola  Diapers   Eggs   Milk
0   True   True  False    False  False   True
1  False   True  False     True   True  False
2   True  False   True     True  False   True
3   True   True  False     True  False   True
4  False   True   True    False  False   True

In [5]:
# Finds the freuency of the item
frequent_itemsets = apriori(df, min_support=0.6, 
                            use_colnames=True) 
frequent_itemsets

   support       itemsets
0      0.6         (Beer)
1      0.8        (Bread)
2      0.6      (Diapers)
3      0.8         (Milk)
4      0.6   (Beer, Milk)
5      0.6  (Bread, Milk)

In [6]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets, 
                          metric="support", 
                          min_threshold=0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beer),(Milk),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,(Milk),(Beer),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,(Bread),(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,(Milk),(Bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [7]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, 
                          metric="confidence", 
                           min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beer),(Milk),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,(Milk),(Beer),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,(Bread),(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,(Milk),(Bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [8]:
rules[rules['support'] == rules['support'].max()]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beer),(Milk),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,(Milk),(Beer),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,(Bread),(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,(Milk),(Bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [8]:
CartItem = ["Milk",]
rules[rules["antecedents"].apply(lambda x : set(CartItem).issubset(set(x)))].sort_values(["support"])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Milk),(Beer),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,(Milk),(Bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [9]:
CartItem = ["Bread",]
rules[rules["antecedents"].apply(lambda x : set(CartItem).issubset(set(x)))].sort_values(["support"])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
3,(Bread),(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75

In [10]:
CartItem = ["Beer",]
rules[rules["antecedents"].apply(lambda x : set(CartItem).issubset(set(x)))].sort_values(["support"])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,(Beer),(Milk),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875

In [11]:
CartItem = ["Diapers",]
rules[rules["antecedents"].apply(lambda x : set(CartItem).issubset(set(x)))].sort_values(["support"])

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []