In [2]:
# !pip install pandas
import pandas as pd
pd.__version__

'2.3.2'

In [3]:
age = [['alex', 32],['rhys', 34],['josh',28],['cristian',35],['dante',34]] #list of list
df = pd.DataFrame(age)
df

          0   1
0      alex  32
1      rhys  34
2      josh  28
3  cristian  35
4     dante  34

In [5]:
data = {'Name':['alex','rhys','josh','christian','dante','abc'], 
        'birthday':[1992,1989,1992,1994,1987,1967],
        'age':[32,30,29,34,36,56]}
df = pd.DataFrame(data) #store the data as frames using "DataFrame()"
df

        Name  birthday  age
0       alex      1992   32
1       rhys      1989   30
2       josh      1992   29
3  christian      1994   34
4      dante      1987   36
5        abc      1967   56

In [8]:
df.head() #first 5 lines of your data

        Name  birthday  age
0       alex      1992   32
1       rhys      1989   30
2       josh      1992   29
3  christian      1994   34
4      dante      1987   36

In [9]:
df.head(2) #will print the 1st two row

   Name  birthday  age
0  alex      1992   32
1  rhys      1989   30

In [10]:
df.tail()

        Name  birthday  age
1       rhys      1989   30
2       josh      1992   29
3  christian      1994   34
4      dante      1987   36
5        abc      1967   56

In [11]:
df.tail(2) #will print the last two row

    Name  birthday  age
4  dante      1987   36
5    abc      1967   56

In [15]:
print(type(df['age']))

<class 'pandas.core.series.Series'>

In [12]:
df['Name']

0         alex
1         rhys
2         josh
3    christian
4        dante
5          abc
Name: Name, dtype: object

In [13]:
df[['Name','age','birthday']]

        Name  age  birthday
0       alex   32      1992
1       rhys   30      1989
2       josh   29      1992
3  christian   34      1994
4      dante   36      1987
5        abc   56      1967

In [11]:
df[['birthday','age']]

   birthday  age
0      1992   32
1      1989   30
2      1992   29
3      1994   34
4      1987   36

In [9]:
i = [1,2,3,4,5,6]
df.index = i
df.index

Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [10]:
df

        Name  birthday  age
1       alex      1992   32
2       rhys      1989   30
3       josh      1992   29
4  christian      1994   34
5      dante      1987   36
6        abc      1967   56

Concat()

In [19]:
import pandas as pd

# Creating two DataFrames
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print (df1)
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
print (df2)
# Using concat
result = pd.concat([df1, df2], ignore_index=True) #to mearge the two table/raws or columns
print(result)

   A  B
0  1  3
1  2  4
   A  B
0  5  7
1  6  8
   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [22]:
# concat by raws

import pandas as pd

df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
print (df1)
df2 = pd.DataFrame({'Name': ['Charlie', 'David'], 'Age': [35, 40]})
print (df2)
result = pd.concat([df1, df2], ignore_index=True)
print(result)

# output

#       Name     Age
# 0   Alice       25
# 1      Bob      30
# 2  Charlie      35
# 3    David      40

    Name  Age
0  Alice   25
1    Bob   30
      Name  Age
0  Charlie   35
1    David   40
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [23]:
# concat by column

df3 = pd.DataFrame({'City': ['Pune', 'Delhi']})
result = pd.concat([df2, df3], axis=1)
print(result)


# output
#        Name      Age    City
# 0     Alice      25     Pune
# 1       Bob      30     Delhi

      Name  Age   City
0  Charlie   35   Pune
1    David   40  Delhi